### ISSUE TITLE
Resurrection (BUG) Not being Interrupted by Combat

### ISSUE THREAD

**Issue by ZetoxZ** [SunwellTracker/issues#592] opened 2018-02-19 19:36 UTC
Decription: 
The Resurrect spell; is not being interrupted by combat.

**How it works:** 
Resurrect is castable OOC, but is not interrupted after being put in combat.
You can also start rezzing out of combat, but will not be able to rez the person if still in combat when the casts ends. 
BUT if you are able to be out of combat when finishing the rez cast you will resurrect them.. This is bugged.

**How it should work:** 
Resurrect should be ONLY be usable OUT of combat; except Druid's Combat Resurrect.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Resurrect

**Comment by set-theorist** [comment] 2018-02-20 18:58
The spell isn't interrupted, but the cast will fail at the end if the target is in combat (in fact, I think it will fail if the target was in combat at any moment during the spellcast). This is probably working as intended.

**Comment by ZetoxZ** [comment] 2018-02-22 03:29
It is not proper behavior at all, any combat SHOULD interrupt and stop resurrect cast. 

Also currently you can go in and out of combat while casting Rez and if you are OOC when it finishes it will go through...that is crazy..Not blizzlike at all

**Comment by ZetoxZ** [comment] 2018-02-22 03:34
It’s actually crazy to think this how it should be..Non Combat Rez has and always will be interrupted by combat, THATS why it’s called that in the first place...lol. Please fix ASAP

**Comment by Shatterx** [comment] 2018-02-22 17:00
Hello, thanks for report, we'll fix it soon.

**Comment by Riztazz** [comment] 2018-02-28 09:28
Resolved with next realm update

**Closed by Riztazz** 2018-02-28 09:28 UTC
