### ISSUE TITLE
Resto druid Clearcasting broken

### ISSUE THREAD

**Issue by Jounkkio13** [SunwellTracker/issues#2715] opened 2019-12-23 08:33 UTC
Decription: 

How it works: 
Resto druid are getting huge amounts of ooc procs on your server im talking about up To 100 is this really how it should work? Iam a resto druid and it feels like im never going oom 

How it should work: 
.. 

Source (you should point out proofs of your report, please give us some source):
http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/details/18/?s=5479&e=5788    **12 procs on retail sindragosa**
http://worldoflogs.com/reports/10erj7dizrosv413/details/19/?s=2619&e=3252   **92 procs on SAP?**  on Frosthold Server 

Casted 5 lifeblooms yesterday In a row because all of them procced ooc? The proc chance should be 6%ish so thats pretty Lucky and that happens guite often

AND when u cast wild growth its almost 100% chance for cc idk If it because it heals 6 targets with glyph this just feels like its wrong can someone confirm im not sure didnt play wotlk much

Ivr heard that for ferals and balance the procs rate is normal but heals are maybe broken

**Comment by Zeorgbugfinder** [comment] 2019-12-23 08:46
really dude? ooc is actually nerfed on this server and it never proc
atleast for balance druid i have glyph of innervate and i can still get oom even in PVE , not even talking about pvp...oom after 2min and then game over....unplayable
ooc never procs on starfall hurricane typhoon

**Comment by styxel** [comment] 2019-12-23 08:52
Well i dont know about balance so i wont go into that maybe the spell is broken all around just for resto the procs are insane

**Comment by Jounkkio13** [comment] 2019-12-23 08:53
For resto druid its proccing like a maniac spell is broken probably completely i dont know about other specs

**Comment by Zeorgbugfinder** [comment] 2019-12-23 09:21
not really in pvp coz it doesnt proc from spells like nature graps,barkskin and in pvp arenas your wild grown sucks so ...

**Comment by styxel** [comment] 2019-12-23 09:36
Okey didnt know that just seems that its proccing very strong with heals for some reason atleast In resto spec.

**Comment by styxel** [comment] 2019-12-23 09:53
https://github.com/SunwellTracker/issues/issues/2500

Feral cat Autoattack seems To work normally here the proc rate is roughly at 3.5ppm 6%. But yeah like i have reported earlier before, Frosthold was Released Omen of clarity has been broken since i didnt play on angra so not sure If its been broken since the beginning of sunwell? No one has ever reported here about this. Basically some stuff aint proccing it which should blizzard made this ability very buggy or hard to manage on priv servers theres always something with it :/. But it can be fixed for sure it has worked perfectly on some other servers.

**Comment by Zeorgbugfinder** [comment] 2019-12-23 09:59
its already reported LONG https://github.com/SunwellTracker/issues/issues/2500
im fucking spaming them to fix it coz i cant play balance druid pvp coz of mana issues and wasting glyph of innervate for pve is not good too

**Comment by styxel** [comment] 2019-12-23 10:02
> its already reported LONG #2500
> im fucking spaming them to fix it coz i cant play balance druid pvp coz of mana issues and wasting glyph of innervate for pve is not good too

Yeah well its holidays seasons now, so im not expecting it to be fixed until 2020 and i dont know how hard it Will be To fix hope fully before ulduar :(

**Comment by styxel** [comment] 2019-12-23 10:14
Looking at logs from our patchwerk kill got 19 ooc procs, out boomkin got 19 and our resto druid had 33 and hes only healing the tanks he casted around 220 times and i did rougly 250melee attacks.

**Comment by Riztazz** [comment] 2019-12-23 12:11
closing, duplicate of https://github.com/SunwellTracker/issues/issues/2715
tagging https://github.com/SunwellTracker/issues/issues/2500

**Closed by Riztazz** 2019-12-23 12:11 UTC
