### ISSUE TITLE
Summon Gargoyle

### ISSUE THREAD

**Issue by KimmoKM** [SunwellTracker/issues#2785] opened 2020-01-06 14:53 UTC
Decription: 
As currently implemented, gargolyte cast speed snapshots to haste (including Unholy Presence) at the moment it is summoned. However, gargoyle cast speed should not be limited by any global cooldown, and currently gargoyle cast speed can go no lower than 1 seconds.

Source (you should point out proofs of your report, please give us some source): 
[Method's Lich King kill on Worldoflogs](http://www.worldoflogs.com/reports/m95i3mcw4ncujkb0/xe/?s=6297&e=7347&x=spell+%3D+%22Gargoyle+Strike%22), demonstrating <1s Gargoyle Strike interval.
[Discussion in MMO-Champion](https://www.mmo-champion.com/threads/697868-Gargoyal-and-Haste?p=7382437&viewfull=1#post7382437) with one of the posters claiming .92s cast time

**Comment by Eradicatepls** [comment] 2020-01-24 15:07
This Bug is currently ruinning the Dk's spec diversity, to be fair, resulting into a very hight representation of frost DK's on your realm.
Fixing this would allow us to play again this wonderfull spec wich is currently not viable in any raid try harding conditions.

**Comment by Eradicatepls** [comment] 2020-01-25 11:12
After a fiew tests it appears that goyle is bolting at it's 1s cast cap with only a Bloodlust and a Meteorite Whetstone Proc, so dumb.
I have a 350 haste pull passive. Haste becomes a pure "Trash Stat" , engineering is busted too. Ghoul is nerfed too cause you can't stack Haste.
We won't be able to run Comet's Trail... And so on.

**Comment by Grozorez** [comment] 2020-01-26 09:20
Please fix  this, so tired of being forced to play frost since Angrathar

**Comment by dariuzsdk** [comment] 2020-01-31 15:02
Would like an update/fix for this, confirmed it affects PvP drastically as well

**Comment by Grozorez** [comment] 2020-01-31 16:28
@Wojtyas @lukaasm @Dootz

**Comment by Dunderj** [comment] 2020-02-01 04:31
Uncapped GCD for Gargoyle would make it deal too much damage because it's already scripted wrong. Blizzlike Gargoyle also did melee as supposed to spam Gargoyle Strike which it currently does on Sunwell. You can see it in the logs you linked http://www.worldoflogs.com/reports/m95i3mcw4ncujkb0/details/84/?s=1657&e=1798

**Comment by DiomacheTharghan** [comment] 2020-02-03 23:23
@Dunderj the fact the Gargoyle WOULD MAKE too much damage is not the point in here since we are not talking about balancing classes but fixing a blizzlike mechanic. Didn't know this was a place where we were defining what's SMALL and BIG, LOW and HIGH. 

That said, i agree with people saying this totally change their playstyle, or their theorycrafting, or their future BiS list planning, not to mention it's ruining their performance with this very same spec. This, without considering PvP, where DK was a top tier class in both 2s and 3s. You guys should really stop to change the focus of this. Gargoyle was working that way in retail, and i don't see any reason if not "we can't fix that", that would avoid the devs to fix that asap, especially because this is a very major problem compared to others that have been fixed within 24-48 hours and not 28 days like this lmao.

**Comment by Dkayzz** [comment] 2020-02-06 12:29
@DiomacheTharghan you misunderstood what @Dunderj said. 
The Gargoyle currently presents two distinct bugs:
1) It only casts spells and doesn't melee (which makes it a lot stronger).
2) It caps haste at 1 second of cast (which makes it a lot weaker).
The two bugs, in terms of power level, cancel (somewhat) each other out. Therefore, they should be fixed at the same time to avoid excessive imbalance in one direction or the other.

**Comment by Grozorez** [comment] 2020-02-06 13:09
You just summon it away from boss hitbox, ure an idiot

This is not okay that a spell does (almost) same damage in Naxx and ICC gear

While we're at it lets nerf warlocks too.

1. Corruption automatically refreshes throughout the fight and warlock dont need to waste a gcd casting it(which makes it a lot stronger).
2. % modifiers dont stay when you reapply it (which makes it a lot weaker).

Makes sense?

**Comment by Dkayzz** [comment] 2020-02-08 00:30
@Grozorez Why would you make stuff up without testing? Gargoyles can't melee in this server, which is a huge boost. Unholy DKs are not being punished by the current state of the Gargoyle.

You can also tell from the logs posted above, in which the gargoyle of a retail ICC geared DK is doing very comparable damage to the goyles in this server.

Makes sense?

**Comment by Grozorez** [comment] 2020-02-22 08:00
47 days and counting, not even a single reply from devs, dogshit server

**Closed** 2020-03-19 19:33 UTC
Labels: Death Knight, Fixed - not live yet

**Comment by markidjani** [comment] 2020-07-11 16:59
Gargoyl cast should be able to go lower then 1 sec but that wont change anything coz his next cast should be limmited by gcd
