### ISSUE TITLE
RAF Not working

### ISSUE THREAD

**Issue by tobi0064** [SunwellTracker/issues#2259] opened 2019-03-26 19:40 UTC
Decription: I hav used RAF, i can see i am linked with him, cause we can summon each other.
We do not get the increased exp rate though, we actually get less exp from mobs now when we are in party than we did before.
And yes we were standing close enough /on top of each other)
we are on friend list
we were in party.
i also still only get x2 exp from quests, like before.
and we cannot grant levels to each other.
we are both lvl 12 now

How it works: 
dont get increasaed exp rate, and cant grant levels

How it should work: 

we should be able to do the above
Source (you should point out proofs of your report, please give us some source):

**Comment by Nadiirr** [comment] 2019-03-31 00:15
> "We do not get the increased exp rate though, we actually get less exp from mobs now when we are in party than we did before."

This is normal because when in a party you get less exp even if your base exp rate increased.

> "i also still only get x2 exp from quests, like before."

Check your actual exp bar. Not just the floating EXP text that shows up in front of you. 

> "and we cannot grant levels to each other.
we are both lvl 12 now"

If you're the same level you can't grant a level to someone.

**Comment by Riztazz** [comment] 2019-04-11 12:58
@Nadiirr already explained everything nicely. Closing as this is not a bug

**Closed by Riztazz** 2019-04-11 12:58 UTC
