### ISSUE TITLE
[Warrior] Heroic Strike Miss 

### ISSUE THREAD

**Issue by zenots** [SunwellTracker/issues#1804] opened 2018-09-03 23:04 UTC
Decription: On retail, when you queue a heroic strike your off-hand white swing was treated as a yellow hit as far as hit chance is regarded.

How it works: Currently if you queue a heroic strike your off-hand white hits are treated as requiring the 24% dual wield hit-cap.

How it should work: Queueing a Heroic Strike should set the base miss rate of melee attacks to the special base miss rate. This eliminates the possibility of crit capping, or becoming rage starved by inconvenient misses in the off hand when mashing Heroic Strike.

Source (you should point out proofs of your report, please give us some source): 
https://gyazo.com/57a56d2c4e6aa10349e13951c7d13959 from the Landsoul Warrior Spreadsheet: https://drive.google.com/file/d/0B0X0dzcVauCGd1haQ20zOUo0dVU/view
http://www.mmo-champion.com/threads/732949-landsouls-spreadsheet
http://www.mmo-champion.com/threads/866092-White-critical-strikes-and-the-attack-table?p=10703474&viewfull=1#post10703474
http://blue.mmo-champion.com/topic/20036-warrior-dps-bugs/
https://github.com/SunwellTracker/issues/issues/1330

How to easily reproduce: Go behind a training dummy (with 8% hit rating) and spam nothing but heroic strike
All Main-Hand swings will be Heroic Strikes, and all Melee swings will be from your Off-Hand. With 8% hit rating (5% gear and 3% fury talents) there should be 0 misses from melee swings.

EDIT: Edited for slight clarification on reproducing, just in case.

**Comment by zenots** [comment] 2018-09-07 21:47
It's an integral part of the way Warrior works in WotLK. Though technically classified as a "bug" on retail, Blizzard was fully aware of it and did not change it due to how important it was for how Warrior worked at the time. The on-next-attack off-hand modifier was not changed until Cataclysm where they removed all on-next-attacks. aka: I'm talking about Heroic Strike in particular but this fix applied to all on-next-attacks like Cleave / Maul. I don't really know all the on-next-attacks though since Warrior was the only one that relied on it with dual wield.

Without this fix Warrior not only sims significantly less DPS (hence why dps warriors are a meme on this server), but it also loses huge amounts of consistency between pulls due to heavy RNG. Basically it means less heroic strikes, which means less slam procs. It also means you get rage starved more often as well as over-cap rage more often due to the huge swings in off-hand main-hand misses vs main hand hits instead being a heroic strike.

In this current state guilds progressing your heroic / modified content have no interest in bringing a Warrior because of their low / inconsistent DPS, when they could just bring another DK and have the rogue+warlock cover the debuffs.

**Comment by zenots** [comment] 2018-09-15 10:56
Is there any way I can help get this looked at faster? I can find some more sources if that would help.

**Comment by Riztazz** [comment] 2018-09-17 21:07
I will look into it probably this week, i just need to finish some stuff first

**Comment by zenots** [comment] 2018-09-18 09:56
Thank you, much appreciated.

**Comment by Riztazz** [comment] 2018-09-29 08:46
Realm has been updated with a fix so im closing this issue, please test and if its still broken please reply to this thread

**Closed by Riztazz** 2018-09-29 08:46 UTC
Labels: In progress, Works locally OR Requires testing, bug

**Comment by zenots** [comment] 2018-09-30 02:50
The fix does not appear to have worked, within 6 offhand swings I already had a miss. I tried a second time with HS bound to mousewheel and spammed it to ensure no offhand swings happened while HS wasn't queue'd, and still had a miss.

https://gyazo.com/ee68f2f082b4c6903dde2330a76e2e85
https://gyazo.com/ca2d155b99b31935f2016d541ef888d3

you can see exactly 28 HS and 28 melee swings using identical weapons.

**Comment by Riztazz** [comment] 2018-09-30 11:05
Yeah issue about penalty being added is definitly resolved but it seems there is another issue elsewhere that we need to track down

**Comment by zenots** [comment] 2018-10-01 00:52
I don't think it's a penalty being added thing, but just that it was a interaction on retail where on-next attacks caused off-hand swings to be considered "special attacks" basically buffing off-hand swing's hit rating, or changing the off-hand from behind considered dual wielding.

I say this not fully sure what you had changed so just kind of trying to understand / cover bases to figure out what it might be?

**Comment by zenots** [comment] 2018-10-04 03:44
https://github.com/dalaranwow/dalaran-wow/issues/3925 looking at when dalaranwow tried to fix it, if I understand correctly "No, this commit is supposed to set your offhand base miss chance to 0 while having Heroic Strike / Cleave queued."

**Comment by Riztazz** [comment] 2018-10-04 05:55
Basically when you roll out an attack, server checks whether you're dual wielding, if you are then you're added hit chance penalty otherwise you're not, i modified that function to check whether you have on next swing type of spell queued and if so you're not added the DW penalty so you require just base value (8%) to hit. Since you're still getting misses (which should occur less less often now) we're having another issue somewhere, could you try reproducing that with 8% hit rating without auras (talents)

**Comment by zenots** [comment] 2018-10-04 06:00
Sure, I'm heading to bed now but will go ahead and bring my hit up to 8% without precision sometime tomorrow either before or after raid and see if that's the issue. Albeit a small sample size, off of the 2 quick tests I did after the fix rolled out it didn't seem like it was happening less, considering it happened within 6 and 28 swings. I haven't watched it in raid much however since we've been mostly focusing on HC Anub with me tanking. :P

**Comment by zenots** [comment] 2018-10-04 20:38
After testing today for 6 minutes on the dummy with 263 hit rating without precision, I did not miss melee swings a single time. It does, in fact, seem that the problem was precision is not applying the 3% hit chance to the off-hand.

**Comment by Riztazz** [comment] 2018-10-05 05:35
It's probably something else :P Can you open a new ticket regarding that and ping me there so i can assign myself and i willl look into it as fast as i can ( lots of stuff to do currently )
