### ISSUE TITLE
[Aces High quest] Heal over time removes combo points

### ISSUE THREAD

**Issue by smkrus** [SunwellTracker/issues#255] opened 2018-02-05 19:11 UTC
Decription: 
Heal over time #3 spell removes combo points

How it works: 
Using #3 heal of time removes your combo points

How it should work: 
As per tool-tip it should add combo point

Source (you should point out proofs of your report, please give us some source): 
In-game tool-tip

**Comment by Riztazz** [comment] 2018-02-05 20:06
No it doesn't, what it does is sets combo points on your new target(you're probably healing yourself so it would be on you) and that's how combo point system works on Wotlk, its not bound to player like on on retail currently it is bound to target you're dealing with

**Comment by smkrus** [comment] 2018-02-05 23:19
Pretty sure I couldn't do 3-3-4 either... which would of been 3 combo pts from 2 heals, then the heal finisher.

**Comment by RoyaxCH** [comment] 2018-02-15 11:15
https://www.youtube.com/watch?v=mH1IREvj138

In this video you perfectly see that the Healing ability places a Combo Point on the Healing target (Mostly yourself).
This means to do 3-3-4 you have to target yourself.

What doesnt work on Angrathar is a Parachute when your Drake dies.

**Comment by Riztazz** [comment] 2018-02-15 12:33
Alright, then it works as intended, i'll fix the parachute part when i find a minute of free time

**Comment by Riztazz** [comment] 2018-02-20 11:58
I just tested it and you do get parachute when your drake dies or you leave it on your own, so im closing this

**Closed by Riztazz** 2018-02-20 11:58 UTC
Labels: In progress, Requires more data
