### ISSUE TITLE
[DK, Spell] Frost Strike can't be Blocked.

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#2644] opened 2019-12-08 07:48 UTC
Decription: 
Frost Strike can't be Blocked.

How it works: 
Frost Strike can't be Blocked.

How it should work: 
Frost Strike should be Blockable.

Source (you should point out proofs of your report, please give us some source): 
https://wow.gamepedia.com/Frost_Strike
"This ability can now be dodged, parried, or blocked. Weapon damage bonus reduced to 55%, down from 60%."

**Comment by Aridam** [comment] 2019-12-08 08:05
Confirmed.

Prepare for FDK PvP to wreck people by denying them their ability to survive longer against their baseline hitter for a while. Welp.

**Comment by BialyADI** [comment] 2019-12-08 12:23
In old Sunwell it worked.
Looks like this Sunwell is more buged than I was thinking.

**Comment by herewegoaganebugs** [comment] 2019-12-08 12:39
ye its in horrible state, they added mythic and improved pve even more, but pve was never the problem people were happy with pve, pvp was really bad, and sad to say now its even worse and more dead.

**Comment by herewegoaganebugs** [comment] 2019-12-08 12:40
why they add all this unblizzlike things to pve, but they cant add 3x honor or 2x flushes per week, or soloq, or anything tbh

**Comment by Aridam** [comment] 2019-12-08 18:24
It seems a lot of past fixes (f.ex. recent Warrior fixes following some of my older reports, as well as year+-old issues regarding Player Pets, and some more) have been broken as a result of further development -- what broke what and when things broke, I don't know for the most part (most I know is when something Warrior-related broke within a few days of some other given past fix). This is where continuous feedback would've been of use, because some much-older reports which have been marked as fixed haven't received any additional feedback in the case of them being broken again.

Though yes, it seems that more fixes are turning up broken as a result. Hopefully it doesn't keep happening and become too much.

**Comment by Riztazz** [comment] 2019-12-09 20:11
Actually, code related to that hasn't changed, it was always like that it seems. rolling out a fix, will be live with next update

**Comment by BialyADI** [comment] 2019-12-10 14:40
That was fast fix, why cant you do it on this two: https://github.com/SunwellTracker/issues/issues/2507, https://github.com/SunwellTracker/issues/issues/2539
They are some kind important issues.

**Comment by Riztazz** [comment] 2019-12-12 08:48
I will fix those as well, working on different thing currently. Closing as this one was fixed already

**Closed by Riztazz** 2019-12-12 08:48 UTC
Labels: Death Knight, Fixed - not live yet
