### ISSUE TITLE
[Anti-Cheat] Auto quest turn-in AddOns make anti-cheat kick their users

### ISSUE THREAD

**Issue by Nuy** [SunwellTracker/issues#2482] opened 2019-11-04 18:19 UTC
Decription: "Auto-complete quest" feature causes Sunwell's anti-cheat to kick player from the server if it spams "Complete Quest" when player is missing required quest turn-in item.

How it works: "Auto-complete quest" feature makes anti-cheat kick its user if it spams "Complete Quest". You can test it on this object for example - https://wotlk.evowow.com/?object=176361

How it should work: Anti-cheat shouldn't kick players from the server because their AddOn is spamming "Complete Quest".

Source (you should point out proofs of your report, please give us some source): -

**Comment by Chumanoyasha** [comment] 2019-11-07 19:39
Confirm!

**Comment by Riztazz** [comment] 2019-11-16 00:13
This is by design, this is a protection against attackers. I'll tweak the numbers a little bit but if you keep spamming that button it will still kick you and i cannot do anything about flaw in said addon, sorry :(
Closing-

**Closed by Riztazz** 2019-11-16 00:13 UTC
