### ISSUE TITLE
Warrior Issues + bg Issues

### ISSUE THREAD

**Issue by xmachinex87** [SunwellTracker/issues#2590] opened 2019-11-30 00:22 UTC
Description:

1: intercept can be dodged/parried = no stun enemy
2: Intimidating Shout breaks from damage even if enemy has absorb shield
3: Heroic Throw resets auto attack timer
4: Charging/Intercepting any imobilize efect like Natures grasp gets you imobilized mid charge
5: Mage is immune to charge stun for like 2 seconds after blinking
bg
1: Falling through texture on charge happens WAY too often
2: If ur defending sota and u die on beach u get ressurected all the way in base

**Comment by Aridam** [comment] 2019-11-30 04:22
> 1: intercept can be dodged/parried = no stun enemy
Already reported.

> 2: Intimidating Shout breaks from damage even if enemy has absorb shield
Is this legit? Provide some proof and make a separate report about it, 'cause that's truly lame for Warriors if confirmed bugged.

> 3: Heroic Throw resets auto attack timer
Intended -- report from long ago actually "fixed" it from working as intended to bugged, my report with proof showed why it's intended for both Heroic and Shattering Throws.

> 4: Charging/Intercepting any imobilize efect like Natures grasp gets you imobilized mid charge
Already reported.

> 5: Mage is immune to charge stun for like 2 seconds after blinking
Intended -- it's in the Spell's description if you read the actual Spell contents found in various WotLK databases.

> 1: Falling through texture on charge happens WAY too often
Make reports with provided proof of where it happens so that developers can try to fine-tune Charge so that it doesn't happen, or find suitable already-made reports which can be updated with that as relevant information.

> 2: If ur defending sota and u die on beach u get ressurected all the way in base
Don't really get what you mean by this. Is this with Graveyards controlled and dying someplace that should 'port you to the closest respective Graveyard if you own it, or what? If so, make a separate bugreport about it and provide both proof and evidence for it.

Overall, lazy work -- does not follow proper bugreport format, and contains misleading information with no proof of any occurrences or evidence of how things are intended to work. Do your homework and redo this as explained.

**Comment by xmachinex87** [comment] 2019-11-30 11:43
Thank you for taking your time, I wrote it at 1am, I will take more time too then, but dont mark my bugtracker post as "homework". I am player not staff. I am gonna make separate post about Intimidating Shout.

**Comment by Aridam** [comment] 2019-12-09 09:11
Close this -- doesn't follow format and lacks a lot of info.

Issue 2 got reported [here](https://github.com/SunwellTracker/issues/issues/2594) and was validated.

**Closed** 2020-03-24 17:10 UTC
