### ISSUE TITLE
[Shaman] Totems

### ISSUE THREAD

**Issue by g3na1997** [SunwellTracker/issues#816] opened 2018-03-07 15:34 UTC
Decription: 
Totems disappear

 if they are put in 0.1-0.2 seconds before the end of their action

How it works: 
Example: if, until the end of the magma totem, there is 0.1-0.2 seconds left and at this point we put the fire totem, then this totem immediately disappears

How it should work: 
Totems should not disappear. Most likely a problem in the exchange of data with the server

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment] 2018-03-07 18:19
I cannot reproduce this issue locally, im guessing its happening when servers update time is quite big. but im gonna push a probable fix that might fix this issue

**Comment by Riztazz** [comment] 2018-03-13 07:18
Should be resolved with next update.

**Closed by Riztazz** 2018-03-13 07:18 UTC
