### ISSUE TITLE
Player's pet / owner : combat issue [Angrathar]

### ISSUE THREAD

**Issue by Hulsuk** [SunwellTracker/issues#1158] opened 2018-04-02 23:37 UTC
Decription: 
Problem with the pet's combat / owner's combat script. [Angrathar]

How it works: 
When a player's pet attack a NPC or an enemy player, the owner is not automatically in combat.
https://youtu.be/30kgGo2wXQI

How it should work: 
When a player's pet is in combat, his owner is in combat too.

Source : 
It is well known but : 

http://wowwiki.wikia.com/wiki/Pet
(https://cdn.discordapp.com/attachments/370202437081890817/430510284122357762/unknown.png)

**Comment by prymex** [comment] 2018-04-08 02:52
Confirmed for warlocks, too. Presumably it's bugged for all pet classes.

Can confirm that pet's combat state isn't linked to owner's combat state at all. This is completely gamebreaking vs any Rogue team in arenas.

Moreover, sending your pet to attack should put you in an unsappable, "soft" combat state, which persists until you command your pet to follow you or stay[1]. While there was a lot of debate during WotLK regarding the legitimacy of this "bug", it stayed in the game at least until Cata[2], which means that it was intended and Blizzlike.

In essence, the fact that there is no combat link between pet and owner means that first, you will get sapped at the start of an arena unless you enter combat with your character; and second, you can be resapped very easily if you don't enter combat with your character.

[1] http://www.arenajunkies.com/topic/72876-pet-combat-bug/
[2] http://www.arenajunkies.com/topic/180753-warlock-cataclysm-warlock-guide-for-the-contest/

**Comment by Danieloses** [comment] 2018-04-09 02:28
I like the part with "intended bug", kys.

**Comment by prymex** [comment] 2018-04-09 18:56
Call it a mechanic if you like. @Danieloses

**Comment by Dootz** [comment] 2018-04-13 20:16
I believe that's what you're looking for:
https://github.com/SunwellTracker/issues/issues/553
Riztazz wrote: 

> You're now able to sap a player whos not in combat even if he sent his pet on target, because we decided to resolve that bug that blizzard had in the past. Also resolved an issue where guardians would instantly set victim in combat rather than when they actually hit him, as far as sending pet on a target behind LoS, ill write it down as ToDo after our movement rewrite. Closing for now

**Comment by prymex** [comment] 2018-04-13 22:03
@Dootz the main point is that any pet's owner does not get combat from their pet when their pet is in combat. As it states in the link attached in the OP, "All pets, with the exception of non-combat pets, will set their owner in combat when they pull aggro." This does not happen. For example, a priest/rogue team could kill my pet behind pillar, and still sap me anytime during that when I should, in fact, be in combat through my pet's combat state.

**Comment by Hulsuk** [comment] 2018-04-13 23:10
More data ?! what oO ?

**Comment by Hulsuk** [comment] 2018-04-13 23:26
More data :
https://youtu.be/FLU2vqlW9Fo

Aggro:
All pets, with the exception of non-combat pets, will set their owner in combat when they pull aggro. However, if the owner can break combat through effects like Feign Death or Flask of Petrification, they will remain out of combat until either they or their pet take another aggressive action. This is true even if the owner mounts, which will dismiss the pet and send any attacking mobs into Evade.

(http://wowwiki.wikia.com/wiki/Pet)
(same mechanic if the target is a player.)

**Comment by Hulsuk** [comment] 2018-04-14 01:03
xD /forfeit

**Comment by ozzyian** [comment] 2018-04-18 17:03
Any eta on this? Really big deal for warlocks and hunters in arena.

**Comment by Azathothh** [comment] 2018-04-20 17:16
"When a player's pet attack a NPC or an enemy player, the owner is not automatically in combat." According to all data stated already in #533 it should work like that.

@prymex "Can confirm that pet's combat state isn't linked to owner's combat state at all. This is completely gamebreaking vs any Rogue team in arenas." 
So you say pet owner should get combat WHEN his pet gets combat, and as a proof post arenajunkies forums topic, where people say that you're NOT GETTING in combat when your pet does...

"basically it consists of you sending your pet in to attack any given target
you aren't in combat according to the game
however, you can not be sapped "
Regarding "hidden" combat - it's already explained here as well: https://github.com/SunwellTracker/issues/issues/553

So far i've seen that pets should give combat to owners only on http://wowwiki.wikia.com/wiki/Pet , but i've seen lots of BS on wowwiki as well - it's not always 100% accurate.
Please find some other proofs, until that i'm closing it.

**Closed by Azathothh** 2018-04-20 17:16 UTC

**Comment by Hulsuk** [comment] 2018-04-23 18:25
@Azathothh It would be nice to know a minimum the game that we intend to script ^^
It's really ridiculous, having to prove the most basic and well-known mechanics of the game
Personally I will not watch 2 hours of hunter 2009 gameplay videos for prove it.
I tested on the current blizzard servers and as soon as the pet goes into combat I also go into combat.
If it's not enouth again..I stop participating in these ridiculous bug report, I let you do as you wish 

https://youtu.be/iUWLq7_wSQ4

**Comment by Azathothh** [comment] 2018-04-24 14:34
@Hulsuk 
No need to watch 2 hours of hunter 2009 gameplay videos - few minutes are enough:
http://www.warcraftmovies.com/movieview.php?id=122825  ~3:10
http://www.warcraftmovies.com/movieview.php?id=152507 ~9:54

**Comment by Hulsuk** [comment] 2018-04-24 15:45
well ok mb
