### ISSUE TITLE
Random heroic queue broken

### ISSUE THREAD

**Issue by mondegoftw** [SunwellTracker/issues#196] opened 2018-02-03 19:49 UTC
Decription:  The random heroic queue doesn't work as it should.

How it works: If a player is saved for every heroic dungeon, the random dungeon queue will return the message "You do not meet the requirements for the chosen dungeons" and not let the player enter the queue.

How it should work: It should be possible to queue for random heroic regardless of saves. Even if a player is saved to only some of the heroics he/she should be able to be let into those instances if he happens to get them through the random heroic queue. Finishing a random heroic gets you saved to said dungeon (unlike the post4.3.0 dungeonfinder), but queueing random heroic is always available.

Source (you should point out proofs of your report, please give us some source): "With random mode on, it will allow you to bypass your normal heroic lockouts."
https://www.engadget.com/2009/12/08/patch-3-3-the-dungeon-finder-guide-page-2/

**Comment by tootin** [comment] 2018-02-03 20:03
I disagree with this the badge gear is a big carry. The beginning of WotLK you could not continue to heroic spam it was on a lockout I remember this because of going for the Oculus void achievements you faced a lock out to get them done. 

The source that is linked here also talks about ToC so this was later in the expansion not the start.

**Comment by mondegoftw** [comment] 2018-02-03 20:09
Can you find a source confirming that you couldn't use the dungeon finder without lockout restrictions in the beginning of wrath? I can't.

**Comment by tootin** [comment] 2018-02-03 20:10
RDF was not in the game until 3.3

**Comment by mondegoftw** [comment] 2018-02-03 20:15
Yes, if the server is trying to emulate WOTLK launch in every aspect, the Dungeon Finder tool should be completely removed. I'm pretty sure that's not what the community wants.

**Comment by tootin** [comment] 2018-02-03 20:19
Were not talking about removing a quality of life improvement from the game like RDF. Your wanting to not be locked to a dungeon that provides faster gearing due to people just endless spamming them. Those badges provide a countless number of things in game that would alter how fast progression happens. Even other things in game like leveling with heirlooms etc.

**Comment by mondegoftw** [comment] 2018-02-03 20:26
Well, you could just as well arbitrarily apply that logic to saying that everything bought with Emblems of Heroism should be twice as expensive as retail prices, or that characters should have permanent res sickness or whatever. I chose to report a bug because there's something in the game that doesn't work the way it did on retail. If the developers choose to ignore it, that's up to them - but it doesn't have any justification in any patch notes.

If they want to emulate WOTLK release, RDF shouldn't be in the game. If they want to use tools from the 3.3.5 patch, random dungeon queues should be unlocked regardless of lockouts. If they want to do neither and arbitrarily redesign the game - okay.

**Comment by tootin** [comment] 2018-02-03 20:58
That is actually close to retail.... You were locked out on retail the same as you are right now. No quantity of item vs the time put in does not even something out like this. The time people will put in just spamming this does not even out. Permanent res sickness, I do not even get what you are referring to here. There is not a bug here because its not like retail at all. Its obvious you did not play this point of retail to know if it was a bug or not.

If the dev's go to change something that big I am sure they will pass a vote on it first with the community. I am sure you will find players on both sides of the fence, but that's the only way I say something like this should get changed.

**Comment by mondegoftw** [comment] 2018-02-03 22:08
I don't know why you're commenting here. You were not locked out on retail like you are on this server. Please provide sources if you're gonna make claims like that.

If you have more personal comments that have nothing to do with bug reports and more to do with in what direction you feel the server should move, I think the forum is a more suitable place for that. The bug tracker is for reporting bugs.

**Comment by dredd-sunwell** [comment] 2018-02-04 17:42
It's not a bug. 4.3 patch note: "Players who use Dungeon Finder for a random Heroic dungeon will no longer be locked to that instance. Previously, players who entered an instance via the Random Dungeon option were then prohibited from queuing for that dungeon or entering the instance manually via the portal. Players should now always be able to complete a specific Heroic dungeon once per day regardless of any random dungeons completed. "

**Comment by mondegoftw** [comment] 2018-02-04 17:53
You haven't read what I wrote then. Here's how it works, which I've described earlier and substantiated with links:

WOTLK (3.3): You GET SAVED from DOING random heroics, but you CAN STILL QUEUE for random heroics EVEN IF YOU ARE SAVED.

CATA (4.3): You DONT GET SAVED from DOING dungeons, meaning you can ALWAYS queue specific dungeon once per day - even if you have already done that dungeon through random heroic.

What you linked is completely consistent with this, so you seem to have misunderstood the meaning of the text you linked yourself.

**Comment by tootin** [comment] 2018-02-04 22:43
I did link you to the support saying it was not available until 3.3. That means you were forced to walk into the dungeon not get teleported to it by lfd. That means you got locked out of the dungeon. Getting teleported to a dungeon was the only way you could avoid the lockout. 

My comments are directed at what you are referring to in your subject as a "bug" it is not technically a bug because of this point in progress on retail wow you had no dungeon finder so were forced to accept lock outs of dungeons. The 3.3 wow version does not mean its at 3.3 in progression its to support it going to that progression. The rewards from vendors for doing these are drastically different so not applying a lockout like it did could change the path of progression completely.

**Comment by mondegoftw** [comment] 2018-02-06 13:52
Any news on this?

**Comment by ujellyx** [comment] 2018-02-08 11:56
I can confirm this bug.
On retail you could spam RDF and if you were lucky you got the same instance multiple times. Here it's not possible because the ID locks you out of the instance completely, even with RDF-queue.

**Comment by Dootz** [comment] 2018-02-27 00:46
That's intended behaviour and thus won't be fixed.

**Closed by Dootz** 2018-02-27 00:46 UTC
