### ISSUE TITLE
[Quest] Unfit for Death

### ISSUE THREAD

**Issue by HuskyHuskyz** [SunwellTracker/issues#275] opened 2018-02-06 10:29 UTC
Description: You are supposed to use the item Pile of Fake Furs on the Nesingwary Traps in order to get credit for the quest. 

How it works: You use the item on the traps, but no NPC spawns and you get no credit.

How it should work: When you use the item, a Nesingwary Trapper should spawn who will run to the trap and die, despawning the trap as well.

Source (you should point out proofs of your report, please give us some source): 
https://www.youtube.com/watch?v=26O8UoxoV3c

**Comment by Bel-WOW** [comment] 2018-02-06 16:20
Did this quest myself yesterday, it was working correctly.

**Comment by TheRealestMcCoy** [comment] 2018-02-12 21:09
The quest does work the issue is the traps are not despawning once used. So they stay visual and people think they are able to use them if some one just did before hand. The fur lays down but nothing else happens. The traps need to be set to despawn after it is triggered by the npc.

**Comment by Dootz** [comment] 2018-04-08 20:02
will be fixed with next server update

**Closed by Dootz** 2018-04-08 20:02 UTC
Labels: In progress, Works locally | Requires testing
