### ISSUE TITLE
[The Sunken Temple] Quest: The God Hakkar

### ISSUE THREAD

**Issue by biscuits69** [SunwellTracker/issues#1462] opened 2018-05-28 05:05 UTC
**Description:**   

This is an interesting chain quest obtained by Yeh'kinya of eastern Tanaris, and the quest chain continues up to Lower Blackrock Spire.  This part is [The God Hakkar](https://classicdb.ch/?quest=3528) where you take this [egg] (https://classicdb.ch/?item=10465) and click it from your inventory by the remains of Hakkar.  The gates to the room close and summoning circles form and minions spawn from them.  

A special mob comes, called [Hakkari Bloodkeepers] (http://classicdb.ch/?npc=8438)--when you kill and loot them you get the Hakkari Blood (http://classicdb.ch/?item=10460).  You use the blood to extinguish the 4 braziers in the room.  Meanwhile, during the event, another special mob comes out, [Nightmare Suppressor](https://classicdb.ch/?npc=8497#comments). You kill those fast because they channel the boss and if they succeed, they cancel the summoning ritual, and the fight ends.

**How it works:**  

My level 80 hunter friend and I did all the above (we killed all the adds, picked up the bloods and extinguished all 4 fires).  As for the Nightmare Suppressors, they went down fast, and I never noticed them disrupting the summoning ritual.  I am confident that his volley spell and pet aggro would have killed them--anyway, I had the last blood and was clicking the 4th brazier and right about that time, during or after, anyway, the gate started to open.  I thought that the boss would come through the door but instead, combat ended and the braziers came on.

I used the egg again and clicked it from my inventory a 2nd time.  We were able to kill 2 of the Hakkari Bloodkeepers and extinguish 2 braziers but the gate opened a second time.  Again, it's quite unlikely that we could have let a Nightmare Suppressor channel its spell, due to the damage we have done.

**How it should work:** 

After you summon and kill the boss, [Essence of Hakkar](https://classicdb.ch/?item=10663) would drop and you'd click it to fill your egg, then you'd get this in its place: [Filled Egg of Hakkar](https://classicdb.ch/?item=10662).  Then turn in to Yeh'kinya, and keep on questing.

Source (you should point out proofs of your report, please give us some source): n/a

**Steps to Reproduce**

In sum, if you were to try to recreate, take a lvl 80 hunter with pet and a level 56 player, and have the lvl 80 kill mobs with volley, including the Nightmare Suppressors.  See if you can get the 4 bloods and extinguish all 4 braziers and summon the boss, with or without the door opening.  If no boss spawns and the door opens and the boss does not fly in, I think there is a bug.

I would also want to know if killing the mobs too fast might cause a bug.  

Finally, thank you for looking into this.  The quest is too interesting to pass up for sake of Lore... that's why I'm on Sunwell.  PS excuse the links are NOT to db.darkwizard.pl--I prefer the other database.

**Comment by Akha72** [comment] 2018-05-28 09:06
It worked perfectly fine for me, but I did it as a party of 5 exping toons and it was some time ago (4/10/18). We managed to spawn Hakkar in a second attempt, because the 1st took us too long.

**Comment by Dootz** [comment] 2018-07-20 14:04
I can confirm that it works now, but you need to kill them quickly. It will be easier from next update.

**Comment by Dootz** [comment] 2018-07-23 20:38
will be fixed with next server update

**Closed by Dootz** 2018-07-23 20:38 UTC
Labels: In progress, Works locally OR Requires testing, enhancement
