### ISSUE TITLE
hellfire ramparts and the blood furnace 

### ISSUE THREAD

**Issue by 2qjskslm** [SunwellTracker/issues#1010] opened 2018-03-20 15:43 UTC
Decription: 
TBC underground city

How it works: I find that the odds of producing something in these 2 underground cities are really amazing! And I also found a lot of people inside farmer gold, and I think it's not a good thing.

How it should work: Reduce the chance of producing it!

Source (you should point out proofs of your report, please give us some source): See a lot of lv80 players go in and out of the 2 Dungeons

**Comment by Soufly** [comment] 2018-03-20 20:37
On every server,those 2 dungeons are on farm for gold,thats not a bug.

**Comment by 2qjskslm** [comment] 2018-03-20 21:24
The probability of producing green items is simply too high to be tolerated. Can you reduce it a little?

**Comment by bongobg** [comment] 2018-03-21 13:41
How do you even consider this as a valid report? This is ridiculous... One of the few ways to grind (literally grind) gold - no bugs are involved here. The drop chance is not that great (same as open world) and half of the reason ppl do that is to farm enchanting mats, not just sell them for gold. Not a lot of TBC dungeons could be soloed with this content to pass Enchanting over 350.

**Comment by Azathothh** [comment] 2018-03-23 16:03
> How do you even consider this as a valid report?
Well...https://www.youtube.com/watch?v=bFSnpICbSu4  - 4 green items in whole instance on retail, while here i've got 26 in whole instance, it's totally a bug.

**Comment by Dootz** [comment] 2018-03-25 11:14
will be fixed with next server update

**Closed by Dootz** 2018-03-25 11:14 UTC
Labels: In progress, bug
