### ISSUE TITLE
[Warrior, Spell] Execute and Sweeping Strikes Damage, almost none.

### ISSUE THREAD

**Issue by BialyADI** [SunwellTracker/issues#2539] opened 2019-11-20 22:35 UTC
Decription: 
Sweeping Strike from Execute have almost no Dmg.

How it works: 
Sweeping Strike from Execute does like 10% of Exe Dmg. On instance, my Execute does 600 Dmg and Sweeping Strike from it do like 60.

How it should work: 
Sweeping Strike should do full Dmg of Exe if second target has less than 20% HP.
And if second target have more than 20% it should do normal swing Dmg.

Source (you should point out proofs of your report, please give us some source): 
https://wowwiki.fandom.com/wiki/Sweeping_Strikes

**Comment by Aridam** [comment] 2019-11-20 23:23
https://imgur.com/a/7ZEiMlg
Tested on Angrathar.
Two Level 76 Dappled Stags, so, same Armor -- no difference in Sweep Damage as a result.
Brought bought down to =<20%HP.
Activated Sweeping Strikes.
Used Execute.
4785 Execute and 4785 Sweeping Strikes.
Working as intended.

**Comment by Aridam** [comment] 2019-11-21 10:04
Nevermind.

_The part about Execute + Sweeping Strikes while one Target is **above** 20% HP is **confirmed**._
https://imgur.com/a/FPtYtMe
>11:56:15> Shroudsoul's [Execute] hits Sinewy Wolf for 1676 Physical.(532 Overkill) 
11:56:15> Shroudsoul has slain Sinewy Wolf! 
11:56:15> Shroudsoul's [Deep Wounds] dissipates from Sinewy Wolf. 
11:56:15> Shroudsoul's [Trauma] dissipates from Sinewy Wolf. 
11:56:15> Shroudsoul's [Sweeping Strikes] hits Sinewy Wolf for 64 Physical.

Again tested on Angrathar.
Same conditions -- two identical Mobs.
Brought _one_ down to =<20% HP.
Activated Sweeping Strikes.
Used Execute.
2208 Execute on that, killing it, _but Sweeping Strikes hit the above-20%-HP one for **64**_.
That's incorrect -- Sweeping Strikes is supposed to do as much Damage as a normal Melee attack (as if you've hit with Auto Attack) on the Target that has over 20% HP if the proc off Execute from hitting the Main Target hits it.
Bug confirmed.
Pardon.

Also, I had reported this long ago [here](https://github.com/SunwellTracker/issues/issues/2420). It seems a recent change has half-broken the fix, in that the super-20%-HP Execute Sweeps are laughably-weaker now. Very broken, basically a waste of Sweep if procced via Execute under these circumstances (works fine if the Sweep victim is also at =<20% HP though).

**Comment by BialyADI** [comment] 2019-11-21 21:16
Very annoying on Arms spec when Execute proc and you have Sweeping Strikes on, plz fix.

**Comment by Aridam** [comment] 2019-11-21 21:32
Yeah this basically makes Execute a waste of Sweep charges, and more.

**Comment by BialyADI** [comment] 2019-12-04 13:33
Bump!

**Comment by Aridam** [comment] 2019-12-09 10:23
More evidence in video format:
https://gfycat.com/gravealarmingacornweevil

**Comment by Riztazz** [comment] 2019-12-12 12:32
Found the issue, gonna fix it in a bit, remember tho - if your primiary target is below 20% health and you use execute on him and your target is not below 20% HP your execute will turn into a normalized weapon damage spell and it's intended, currently it always assumes the latter (before my fix)

**Comment by Aridam** [comment] 2019-12-12 12:34
But what about the Damage? As shown, it's puny -- far-lower than normalized Melee (Auto Attack) Damage when procced via super-20%-HP Execute Sweeps.

**Comment by Riztazz** [comment] 2019-12-12 14:19
Sub 20% executes which triggers SS proc will check if SS proc target is also below 20% health, if so then normal execute dmg will go thru - otherwise it will be normalized weapon damage (a blizzard spell) and it's how it's supposed to work in this case

**Comment by Aridam** [comment] 2019-12-12 17:29
Yes I know already, but what I mean is, as shown in initial tests _and_ in my bumping of this issue with video evidence, you can see the super-20% procs were puny two-digit numbers which are _definitely_ bugged Damage values (considering my AAs hit for 3-/4-digit values) -- will that be fixed as well, is what I'm asking.

**Comment by Riztazz** [comment] 2019-12-13 09:51
That's another issue alltogether but i will fix it later, gonna push one fix for execute for now, keeping this open.

ToDo:
Fix damage calculations for SS executes

**Comment by Riztazz** [comment] 2019-12-13 09:58
Actually, it should fix itself as well after my fix, please test after realm update

**Comment by Riztazz** [comment] 2019-12-13 10:38
Closing, lemme know in an answer if everything is fine - if not, i'll reopen

**Closed by Riztazz** 2019-12-13 10:38 UTC
Labels: Fixed & Implemented, Fixed - not live yet, Spell system, Warrior

**Comment by Dunderj** [comment] 2020-01-14 02:07
Still bugged 
http://www.worldoflogs.com/reports/hdcdzr5bzpx8c0b0/xe/?s=5133&e=5294&x=spell+%3D+%22Sweeping+Strikes%22%0D%0AAND+amount+%3C+100%0D%0AAND+amount+%3E+1

**Comment by Riztazz** [comment] 2020-01-21 09:30
Not a bug, target has below 20% health but slimes do not - hence you're getting normalized weapon damage for slimes and execute damage for main target. If slimes were below 20% health you would copy executes damage instead
