### ISSUE TITLE
Quest The Stones that Bind Us

### ISSUE THREAD

**Issue by Yebyemnetho** [SunwellTracker/issues#2586] opened 2019-11-29 08:21 UTC
Decription: 
Some of binding stone in this quest are untargetable, befor mob gets aggro and when he get his immune to dmg buff.
How it works: 
you should attack binding stones when servants get immune to dmg, but some stones are not targetable, you cant do nothing with them

How it should work: you should attack binding stones when servants get immune to dmg

Source (you should point out proofs of your report, please give us some source):

**Comment by Aridam** [comment] 2019-11-29 10:11
Cannot reproduce.
Try next to the Stones themselves -- both you and the Mob being next to it, up to a few yards.
See this footage as an example:
https://youtu.be/C4MknDnsLAg?t=43

If it doesn't work, reposition yourself and try again to hover your mouse over it, until it turns into a cogwheel icon marking it as usable.

**Comment by Dootz** [comment] 2020-01-04 21:50
Hi,

this seems to be working correctly, if you or anyone else will encounter issue with this quest, please open a new issue.

**Closed by Dootz** 2020-01-04 21:50 UTC
Labels: Quest
