### ISSUE TITLE
RDF Heroic Dungeon lockout

### ISSUE THREAD

**Issue by Dolice1990** [SunwellTracker/issues#684] opened 2018-02-26 15:40 UTC
Decription: 
the RDF on Angrathar is bugged there are several forum posts on google showing proof RDF let you queue for Random Heroics regardless if you were Locked or not right from the get go, now some of these posts i'm about to link are from 2009 (patch 3.3) however you WAS allowed to spam RDF Heroics as much as you pleased 

https://github.com/Atlantiss/BugTracker/issues/3394

https://blue.mmo-champion.com/topic/1545-07-12-dungeon-finder-tool-mini-faq/   (blue post)

https://www.mmo-champion.com/threads/1208640-How-do-Heroic-lockouts-work

https://www.engadget.com/2009/12/07/dungeon-finder-tool-mini-faq/

also attached is a screenshotted chat with a gm (Shatter) saying the RDF finder is based on 3.3.5

so this needs to get fixed

How it works:  queue for rdf heroic, complete all of them then you can't requeue

How it should work: you should be able to only do SPECIFIC heroics once per day then you get locked, however you can still get the same heroic regardless of lockout if you queued with the random dungeon finder 

Source (you should point out proofs of your report, please give us some source):  sources are above also heres the screenshot of the gm chat i had http://sunwell-community.com/uploads/monthly_2018_02/gmchat.jpg.2701210525daa5eca745f749b432c8df.jpg

on top of that don't lie to me saying the server is on Patch 3.0.1 or whatever when it's clearly 3.3.5 because there is Badge of Frost and other content gear we don't have access to readily available to buy in Dalaran

**Comment by ujellyx** [comment] 2018-02-26 16:04
Duplicate of https://github.com/SunwellTracker/issues/issues/196

Too bad this isn't on the dev's priority list though...

**Comment by Dolice1990** [comment] 2018-02-26 16:18
ye sry thank you

**Closed** 2018-02-26 17:38 UTC
Labels: duplicate

**Comment by Dootz** [comment] 2018-02-27 00:46
That's intended behaviour and thus won't be fixed.
