### ISSUE TITLE
Ardent Defender (Paladin protection talent point 3/3) not working

### ISSUE THREAD

**Issue by Artanis02** [SunwellTracker/issues#1905] opened 2018-10-29 22:41 UTC
Decription: 
Ardent Defender (Prot Paladin's seventh tier talent point (on the right)) does not proc when taking a hit that would otherwise kill me.

How it works: 
The hit that is about to kill me doesn't proc Adent Defender and the character just dies. (No healing occurs)

How it should work: 
After being hit with an attack that would otherwise kill me, the character should be up to 30% of max health (dependant on defense).

**Comment by Artanis02** [comment] 2018-10-29 23:14
GM asked me to wait until higher level and see it the problem persists.

**Comment by Cwiercpasiec** [comment] 2018-10-31 23:36
And what was your defense at that moment?

**Comment by minimoncho** [comment] 2018-11-01 20:00
But it didn't proc at all? or you got the debuff but no heal?
If it's the latter your defense rating might be too low to notice the heal

**Comment by Artanis02** [comment] 2018-11-01 20:51
It didn't proc and there was no effect (the effect looks like a resurrection) and no debuff ¯\_(ツ)_/¯

**Comment by ryan1pepin** [comment] 2020-06-06 14:34
confirm it procs AFTER DEATH as a sub 50 paladin(confirmed via combat log).
![image](https://user-images.githubusercontent.com/14218000/83946835-44161700-a7e1-11ea-9e87-600ad904126e.png)

image of all my active spells fading off as if i'm dead and then ardent defender uselessly proccing. confirmed happening atleast 3x.

**Comment by ryan1pepin** [comment] 2020-06-06 17:35
> or you got the debuff but no heal?

I get the debuff (once dead) but no heal. I have not confirmed if the damage reduction portion of the talent is working or not but I assume it is.

**Comment by Artanis02** [comment] 2020-06-07 07:49
From what I remember, it never worked on at low levels. Maybe because of low/no defense rating?

**Comment by Rosenkrantz** [comment] 2020-06-07 21:24
You need *additional* defense rating to make it work. If you have 0 defense on gear = 0 heals for you.

**Comment by ryan1pepin** [comment] 2020-06-07 22:17
I have some defense, but probably less then 30. Looking at the WOTLK patch notes for ardent defender I found this

example: a paladin with defense equal to only 5 times his or her level will receive no healing from the talent, while a paladin who is immune to critical strikes from boss creatures through defense will receive the maximum amount).

So this is working as intended. Sorry about that! feel free to close this.

**Comment by Artanis02** [comment] 2020-06-08 03:12
can you link the sourse?

**Comment by ryan1pepin** [comment] 2020-06-08 13:06
https://wowwiki.fandom.com/wiki/Ardent_Defender
patch 3.2.0 notes

**Closed** 2021-03-17 13:55 UTC
Labels: Invalid/Wrong Issue, Spell system
