### ISSUE TITLE
Shadowform + Dispersion + Mounted = Greyed out Shadowform?? [Resolved]-ish

### ISSUE THREAD

**Issue by CristenPerret** [SunwellTracker/issues#2683] opened 2019-12-16 08:29 UTC
Decription: 
In Shadowform, and mounted (ground or flying) Cast Dispersion, and before the duration of Dispersion ends. Leave shadowform.

How it works: Dispersion removes the playermodel, and when the unit is mounted it seems to not refresh the model back without the end effect of dispersion taking place.

How it should work:  Not be invisible. (mechanically still visible to NPCs, not players)

I decided to take the testing a bit further, and kinda whoopsied my character...
During ["Cold hearted"](https://www.wowhead.com/quest=12856/cold-hearted)
I had this model bug happen, while transfering from my flyermount (nomodel), to the Quest NPC Drake (Mount). This ended up resetting my player model, so I was visible again.

HOWEVER I CANNOT GO INTO SHADOWFORM AGAIN!
I have died a few times, D/C'd, and tried /cancelaura shadowform, and I cant enter Shadowform. The spell in my spellbook is darkened. Hopefully server reset might fix it, lol good thing imma healer..

My IGN is Dumsperman (Alliance) [_Video_](https://youtu.be/1MG96r4hR98?t=28)

**Comment by Aridam** [comment] 2019-12-16 09:10
You can't do `/cancelaura Shadowform` purely because you're not _in_ Shadowform -- you canceled it _during_ Dispersion while mounted, for the intent of recreating this glitch -- the actual bug is in this interaction causing Shadowform to be __not usable_. It's still odd that relogging doesn't fix that -- the infamous grayed-out Raise Dead bug from years back used to be fixed on the player's end through relogging, for example. Would swapping between Talent Specs or resetting work?

Video at the timestamp shortly shows (before UI gets hidden again) that Shadowform _isn't_ grayed-out on the Action Bars down there. At the end of the video, you also see the Priest casting Shadowform while on his Mount, which pops his model back on.

Confirmed.

**Comment by CristenPerret** [comment] 2019-12-16 16:35
So its fixxed now. Im not sure if my logging out lastnight was too short to count, or if the server restart did it. Spec changes did nothing either.
The bug doesnt greyout normally, but when being juxtaposed from one mount to another while the model is missing is what causes such a critical issue.

**Comment by Piootrek** [comment] 2020-01-24 20:40
Issue with player model is client bug. Can't be fixed by us.

**Closed by Piootrek** 2020-01-24 20:40 UTC
Labels: Priest
