### ISSUE TITLE
[Angrathar] [Quest] [DragonBlight][Torture the torturer]

### ISSUE THREAD

**Issue by Amalurs** [SunwellTracker/issues#692] opened 2018-02-26 20:12 UTC
Decription: 
Torturer Lecrafty hits too much as he spams a spell non stop that hits like 500-600 but he casts it like 10 times a second.

How it works: He hits too much and you cant use the item 5 times at it is requried bc it does too much dmg.

How it should work: Deal less dmg so the quest can be completed

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment] 2018-02-26 22:13
Hi could you provide some evidence (like screenshot of Combat Log) ? Also which spell? He's supposed to cast Kidney Shot every 20 - 25 seconds, and his second ability Hemorrhage is even more rare.

**Comment by Amalurs** [comment] 2018-02-26 22:19
Unfortunately I didnt make a screen but im sure he will do that if you
engage him,killed me 3 times even almost oneshoted my earth elemental,the
spell he did had an effect like a horizontal moonlike shape,hope it helps

On Feb 27, 2018 12:14 AM, "Chris" <notifications@github.com> wrote:

Hi could you provide some evidence (like screenshot of Combat Log) ? Also
which spell? He's supposed to cast Kidney Shot every 20 - 25 seconds, and
his second ability Hemorrhage is even more rare.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SunwellTracker/issues/issues/692#issuecomment-368669875>,
or mute the thread

**Comment by bongobg** [comment] 2018-02-27 07:28
I did this quest a day or 2 ago and thank God I'm a tank. A screenshot could hardly be an evidence as the issue is with his attack speed. It's just ridiculous insane, like 0.01, and you have to live through 5 uses of the Q item. Stack dodge. :D

**Comment by xStiven** [comment] 2018-02-27 08:01
I confirm this bug, because of his crazy attack speed the npc literally killed himself troughs my char retro aura before quest item cd allowed to stump him 5 times as quest requested. So it was problematic to complete the quest, but it is doable. Cloth classes probably would have A LOT of pleasant word about this quest.

**Comment by Dootz** [comment] 2018-03-04 22:56
Will be fixed with next update.

**Closed by Dootz** 2018-03-04 22:56 UTC
Labels: In progress, bug
