### ISSUE TITLE
[CoS - trash]

### ISSUE THREAD

**Issue by franXter** [SunwellTracker/issues#817] opened 2018-03-07 18:09 UTC
Decription: 
When doing CoS hc the first group of infinite (the humans that transforms into dragonkins in the house after the 2nd boss) dispawned a second after they go active. I've seen it happen twice for no apparent reason. All members of the party were standing close to them.

How it works: 

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by ujellyx** [comment] 2018-03-08 11:29
Duplicate of https://github.com/SunwellTracker/issues/issues/574

**Closed** 2018-03-08 14:23 UTC
Labels: duplicate
