### ISSUE TITLE
[NPC] [Event] Culling of Stratholme - Infinite Dragons

### ISSUE THREAD

**Issue by Danielmkd21** [SunwellTracker/issues#574] opened 2018-02-18 14:33 UTC
Decription: After the second boss in Culling of Stratholme - Salramm the Fleshcrafter and before the third one, there are 4 packs of Infinite Dragons, coming out of portals. Each pack has 1 Infinite Agent which is also objective of the daily dungeon quest "Timear Foresees Infinite Agents in your Future!". For the quest you need to kill 4 Infinite Agents. that means to clear all the packs. The problem is that sometimes the first pack just dies instantly/disappears and people can't complete the daily dungeon quest.

How it works: In the last 2/3 times I've been in CoS HC the first pack just disappeared. 

How it should work: All the mobs should come out of the portals normally and do not disappear.

Source (you should point out proofs of your report, please give us some source): 
http://wowwiki.wikia.com/wiki/Quest:Timear_Foresees_Infinite_Agents_in_your_Future!
http://wowwiki.wikia.com/wiki/Culling_of_Stratholme

**Comment by Riztazz** [comment] 2018-02-20 15:28
Cannot reproduce but i've got a feeling that its arthas that's killing them, ill make some tweaks to the code. Lemme know if it fixes it or not (check changelog when its on the realm ;p)

**Comment by RoyaxCH** [comment] 2018-02-23 10:29
They actually disappear. After you kill them they're lootable for like a splitsecond and after that disappear. Same happened to me before actually killing them, making the Daily heroic in Stratholme unsolvable.

**Comment by ujellyx** [comment] 2018-02-24 09:28
After around 15 good runs this happened to me for the first time today... GM had to complete the daily dungeon quest, because one can't complete it without the first pack.
The pack despawned right before they transmorphed into the infinite-thingies.

**Comment by Dootz** [comment] 2018-05-16 14:51
hopefully fixed with last update

**Closed by Dootz** 2018-05-16 14:51 UTC
Labels: bug
