### ISSUE TITLE
Old dailies can't be shared.

### ISSUE THREAD

**Issue by qruz1337** [SunwellTracker/issues#1327] opened 2018-05-01 08:26 UTC
Decription: 
In retail wrath of the lich king, old dailies from previous days were eligible to be shared with friends. This doesn't work on this server, but it would make sense that it should.

How it works: 
When you press the share button, no error message pops up. Nothing happens

How it should work: 
The quest should be shared with your eligible party members.

Source (you should point out proofs of your report, please give us some source):

**Comment by Dootz** [comment] 2018-05-01 10:10
Hi! Could you give me an example of such quest? I'll look into this.

**Comment by qruz1337** [comment] 2018-05-01 23:11
Daily heroic and daily dungeon are the most concrete examples of these quests that I can give.

**Comment by Dootz** [comment] 2018-05-02 19:40
I checked dailies for dungeons and they seem to be shareable. What most likely happens is, the person you're trying to share it to already completed daily or have one already in questlog.

**Comment by qruz1337** [comment] 2018-05-04 03:05
[![Screenshot from Gyazo](https://gyazo.com/54ea50c335653c2b5524ba552075687c/raw)](https://gyazo.com/54ea50c335653c2b5524ba552075687c)

I mean something like this. Press the button, nothing happens. The character receiving the daily doesnt have the daily heroic quest completed that day.

**Comment by Dootz** [comment] 2018-05-13 16:56
from what i've heard, that's intended behaviour, and won't be fixed.

**Closed by Dootz** 2018-05-13 16:56 UTC
Labels: Works locally | Requires testing, wontfix
