### ISSUE TITLE
Nitro Boosts - cooldown

### ISSUE THREAD

**Issue by Walazar** [SunwellTracker/issues#2260] opened 2019-03-27 21:47 UTC
Decription: 
Nitro boosts "tinker" from Engineering. 

How it works: 
I personally play 79 twink and I think some twinks have multiple pairs of boots, where they put nitro boosts on each pair. The cooldown of Nitro Boost in general is 3 minutes, but if you switch your boots with a new one with also Nitro Boosts, the cooldown is now 30 sec. So in fact they can use nitro boosts 6 times where only 1 time should be 'right'

How it should work: 
When Nitro Boosts is used the cooldown should be 3 minutes no matter what.

Source (you should point out proofs of your report, please give us some source): 
Proof: I was suspicious someone of using it and I tried it myself if it worked (just in dalaran), and it did.

**Comment by Riztazz** [comment] 2019-04-11 12:44
So i've just tested and it's nothing like ticket says.
I've got 3 pairs of boots with nitro enchant in my bag and one on me, whenever i use the ones i have on me, all other pairs get 3minute cooldown as well.
Unless i'm doing something wrong - this is working as intended. Keeping this alive for a week while i wait for more information otherwise i'll close the issue

**Comment by Azathothh** [comment] 2019-04-11 13:58
It appears that cooldown on other pairs of boots activates only if they are same as the boots that you've used nitro on.
![obraz](https://user-images.githubusercontent.com/37483678/55962960-2fd49980-5c72-11e9-9c48-5fdea2b6a884.png)
2x Boots of the Funeral March and Blood-Soaked Saronite Stompers on screen, all with Nitro Boosts enchant
Nitro Boosts used on Boots of the Funeral March activated Nitro Boosts cooldown of other pair of Boots of the Funeral March, but didn't activate cooldown on Blood-Soaked Saronite Stompers,  so yeah, it's bugged.

**Comment by Riztazz** [comment] 2019-04-11 14:14
alright

**Comment by Riztazz** [comment] 2019-04-24 14:06
Cooldown visibility is handled client-side actually :/ I'll prevent cooldown override server-side and player won't be able to use those but as far as client visibility goes - it has to stay like that

**Closed** 2019-04-27 12:21 UTC
Labels: fixed
